apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-volume-claim
  namespace: sns
spec:
  accessModes:
    - ReadWriteOnce # 로컬 실습시에는 이렇게 설정해야 함
  storageClassName: local-sns-storage
  resources:
    requests:
      storage: 100Mi